image: docker:stable

services:
- docker:dind  

before_script:
- echo "$CI_REGISTRY_USER $CI_REGISTRY_PASSWORD"
- docker info 
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
    stage: build
    script: 
    - docker build -t minha-imagem .