image: docker:stable

services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
    stage: build
    script:
    - docker build -t minha-imagem .
    - docker tag minha-imagem 272001/minha-imagem:latest
    - docker push 272001/minha-imagem:latest