image: docker:stable

services:
- docker:dind

before_script:
- echo $CI_REGISTRY_USER
- echo $CI_REGISTRY_PASSWORD
- docker info
- docker login -u $CI_REGISTRY_USER --password-stdin

build-docker:
    stage: build
    script:
    - docker build -t minha-imagem .
    - docker tag minha-imagem 272001/minha-imagem:latest
    - docker push 272001/minha-imagem:latest