image: docker:stable

services:
- docker:dind

before_script:
- docker info
- docker login -u 272001 -p Richard10Docker

build-docker:
    stage: build
    script:
    - docker build - t minha-imagem .